### ISSUE TITLE
Creating non-neighbouring IPv6 addresses 

### ISSUE THREAD

**Issue by TheBigBen1** [dukaev/ipv4-ipv6-proxy#10]
Hi Dukaev,

thank you for this package. It is incredibly powerful and still very easy to use.

I was wondering if it it possible to create IPv6 addresses that are non-neighboring? As all my IP addresses now start with the same format (e.g. "2001:20c:1f15:" - this is not a real address). Is there a way to truly randomly generate IPv6 addresses? 

Thanks so much again for all your work! 
Best,
Ben

**Comment by dukaev** [comment]
Hello!
Thank you for using it 🙂

It generates random IP addresses based on your subnet.
Source: https://github.com/dukaev/ipv4-ipv6-proxy/blob/master/scripts/install.sh#L7
and https://github.com/dukaev/ipv4-ipv6-proxy/blob/master/scripts/install.sh#L92

**Comment by TheBigBen1** [comment]
Thanks for the fast answer!

Probably very stupid question: It is probably not possible to create IPv6 addresses outside of your IPv6 subnet right?

I am using the tool on a site and after ~200 requests they block all Ipv6 addresses that I generated on a server (even the ones that I did not use yet), so I assume that they just block the whole subnet.

**Comment by dukaev** [comment]
Yeah. They blocked all your subnet :(

**Comment by TheBigBen1** [comment]
Ok too bad :/ Thanks again for your help
