### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by kadirphp** [dukaev/ipv4-ipv6-proxy#11]
Hello.

I installed the proxy as you specified.
"ERR PROXY CONNECTION FAILED"
I get the error, when I restart the server, the connection is made for a while, but then the connection is lost again.
I'm using Vultr.

Thanks.

**Comment by dukaev** [comment]
Hello!
Thank you for using script.
After the restart, config for e.g iptablses are resetting.

Why you need a restart server?

**Comment by kadirphp** [comment]
Hello.

When the internet didn't work, I wanted to reboot.The connection is maintained for 3-4 minutes during each restart, but after 3-4 minutes it is disconnected again.I installed servers in 3-4 different locations, they all have the same problem.I watched the video as if there was something I missed, but I'm sure I did what happened in the video.As I said, the connection is provided for the first 3-4 minutes, then disconnected from all over, or from scratch installation.

Take care, Thanks.

**Comment by dukaev** [comment]
Instead `reboot` try:
```sh
stacksize 262144
ulimit -n 65536
service 3proxy restart
```

**Comment by kadirphp** [comment]
Hello.

I did what they said, but the result is still the same, after 3-4 minutes the internet goes.

**Comment by dukaev** [comment]
@kadirphp are you using server for 10$ in vultr?

**Comment by kadirphp** [comment]
@dukaev Yes, I tried $ 5, $ 10, $ 20.
