### ISSUE TITLE
Proxy crash after few minutes.

### ISSUE THREAD

**Issue by s00ny5** [dukaev/ipv4-ipv6-proxy#14]
Ok,

So I installed on a 10$ vultr vps and all went smooth.

Problem is the proxy works for like couple of minutes and after I get proxy refuse connection.

Any idea ?

**Comment by dukaev** [comment]
This behavior started appearing three days ago. I don't know why yet

**Comment by s00ny5** [comment]
Any logs I can check and eventually post here the results ?

Regards

**Comment by dukaev** [comment]
You can step by step enter commands to terminal to see behavior
https://github.com/dukaev/ipv4-ipv6-proxy/blob/master/scripts/install.sh

**Comment by dukaev** [comment]
ulimit -n 10048
