### ISSUE TITLE
Getting IPV4 and IPV6 ip`s some time fail

### ISSUE THREAD

**Issue by s00ny5** [dukaev/ipv4-ipv6-proxy#15]
So about 1 in 2 installs the getting ip curl will fail and give this error:
![image](https://user-images.githubusercontent.com/30322461/81976874-d9364d80-9631-11ea-9a95-ad59cec02d40.png)

Any idea how to do it again if error ? as of now I install the whole vps again.

Regards

**Comment by dukaev** [comment]
Thank you for detecting the problem!
script used ifconfig.co for detect IP

**Comment by dukaev** [comment]
@s00ny5, please reinstall and try the script. I fixed

**Comment by dukaev** [comment]
(fixed now)

**Comment by s00ny5** [comment]
I saw that in the install script.
I switched to `icanhazip.com` and all fine.

Still testing
