### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mzaboss** [dukaev/ipv4-ipv6-proxy#2]
Hi, good work here. but i am getting error below:

Service not started on line: 14
Command: 'proxy' failed with code 40, line 14

any advice?

**Comment by dukaev** [comment]
Hello @mzaboss! 
Did you run this on centos 7?

**Comment by mzaboss** [comment]
Hello @dukaev 

[root@mzalinux ~]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

Yes sir.

**Comment by dukaev** [comment]
Did u added ip6 support?

**Comment by mzaboss** [comment]
I am using different VPS provider. (Shape.host) and i believe its enabled.  

https://gyazo.com/a378c8f1aa4feaf1f7e3fdaf4038970b

https://youtu.be/a8zQM4pBViU

**Comment by dukaev** [comment]
Ok. Show me `ifconfig`

**Comment by mzaboss** [comment]
[root@mzalinux anal]# ifconfig
eno16777752: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 66.70.150.150  netmask 255.255.255.224  broadcast 66.70.150.159
        inet6 2001:db8:1000::100  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::1c00:6fff:fe00:f7  prefixlen 64  scopeid 0x20<link>
        ether 1e:00:6f:00:00:f7  txqueuelen 1000  (Ethernet)
        RX packets 146024113  bytes 21679627199 (20.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 97142884  bytes 7343676560 (6.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 14  bytes 844 (844.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 844 (844.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@mzalinux anal]#

**Comment by dukaev** [comment]
Ok. Have you installed 3proxy before?
I think problem in 3proxy. Check version. It should be 0.8.6

I see two ways:
- Vultr. It definitely works there.
- Understand the problem. Step by step enter the commands that are responsible for the installation 3proxy.

```shell
yum -y install gcc net-tools bsdtar zip

URL="https://github.com/z3APA3A/3proxy/archive/3proxy-0.8.6.tar.gz"
wget -qO- $URL | bsdtar -xvf-
cd 3proxy-3proxy-0.8.6
make -f Makefile.Linux
mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
cp src/3proxy /usr/local/etc/3proxy/bin/
cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy
chmod +x /etc/init.d/3proxy
chkconfig 3proxy on
```

**Comment by mzaboss** [comment]
https://gyazo.com/fa15e50293e8a3d7da40c847f100112d

still error.. ;/ got team viewer?

**Comment by phunghv** [comment]
How to solve this problem guys?
