### ISSUE TITLE
I managed to create proxys but its not connecting to websites

### ISSUE THREAD

**Issue by deekshithCcc** [dukaev/ipv4-ipv6-proxy#26]
Hey proxies are not connecting to websites, please update the script.

Thank you.

**Comment by SuperWinur** [comment]
I also have this same issue, anyone know how to fix?

**Comment by manashan** [comment]
I also have this issue how did you guys fix it?

**Comment by johnsen1983** [comment]
I also have this same issue, anyone know how to fix?
