### ISSUE TITLE
SIOGIFINDEX: No such device

### ISSUE THREAD

**Issue by UgurKacak** [dukaev/ipv4-ipv6-proxy#3]
After entering proxy count, that gives an error. On centos. Private VPS that can be access with ipv4 and going out  internet ipv6.

```
Internal ip = myipv4. Exteranl sub for ip6 = myipv6
How many proxy do you want to create? Example 500
1
chmod: cannot access ‘boot_*.sh’: No such file or directory
SIOGIFINDEX: No such device
SIOGIFINDEX: No such device
Starting 3Proxy

SIOGIFINDEX: No such device
SIOGIFINDEX: No such device
Starting 3Proxy

SIOGIFINDEX: No such device
SIOGIFINDEX: No such device
Starting 3Proxy

```

**Comment by haliluunal** [comment]
Scriptte ethernet kartı eth0 olarak tanımlı, scripti kendi ethernet kartınıza göre düzenlerseniz sorun çözülür

**Comment by Kalvelign** [comment]
https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-change-network-interface-name-to-eth0-on-centos-8-rhel-8.html
