### ISSUE TITLE
The proxy server is refusing connections

### ISSUE THREAD

**Issue by manashan** [dukaev/ipv4-ipv6-proxy#30]
Hi, I managed to create proxies but they don't work.
How can I fix this problem? I get this from Firefox

The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.

**Comment by mumiix1** [comment]
Hello sir, did you solved it? i have the same issue?

**Comment by Kalvelign** [comment]
solve ?

**Comment by dukaev** [comment]
fixed
