### ISSUE TITLE
Proxy fail to works after some days

### ISSUE THREAD

**Issue by BrokedTV** [dukaev/ipv4-ipv6-proxy#5]
Hello Dukaev, 
I have been using your scripts for some days and it's really great and easy to deploy.
I have found out that on multiple servers, after some days the proxies stop working as they used to, they refuse most of the connection requests, sometimes they works often they don't. It's a really strange issue that i don't understand where it comes from, server CPU is low, bandwidth is not full.
If you have any suggestion that would be very appreciated!

**Comment by dukaev** [comment]
Hello 👋 @BrokedTV
In manual restart 3proxy: `service 3proxy restart` or `service 3proxy stop && service 3proxy start`

For the fix, this bug you need add auto-restart 3proxy after the crash. I don't know how to solve this problem yet. Maybe with systemd like https://unix.stackexchange.com/questions/486417/systemd-restart-service-automatically-only-after-crash

**Comment by BrokedTV** [comment]
Really appreciated your reply Dukaev!
It actually was just 3proxy crashing or closing for some reason, using "systemctl restart 3proxy.service" made it restart and get back to works, i will look into an automated way to do this in case it crash again, but still great to save those servers!
Thanks, if you have a tip jar somewhere feel free to share it!
